POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
      "id":4,
      "titulo": "Bootcamp SQL",
      "lenguaje":"SQL",
      "vistas":"23000",
      "nivel":"basico"
}
###
PUT http://localhost:3000/api/cursos/programacion/4 HTTP/1.1
Content-Type: application/json

{
      "id": 4,
      "titulo": "Bootcamp MYSQL",
      "lenguaje":"MYSQL",
      "vistas":"23000",
      "nivel":"medio"
}

###
PATCH http://localhost:3000/api/cursos/programacion/4 HTTP/1.1
Content-Type: application/json

{
      
      "titulo": "Camp MYSQL",
      "vistas":"53000"
}

###
DELETE http://localhost:3000/api/cursos/programacion/3 HTTP/1.1